name: gogo_cookie_gen

on:
  schedule:
    - cron: '*/10 * * * *'  # runs every 10 minutes

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests bs4
          
      - name: execute py script
        env:
          GOGO_EMAIL: ${{ secrets.GOGO_EMAIL }}
          GOGO_PASSWORD: ${{ secrets.GOGO_PASSWORD }}
        run: python something/gogo_cookie_gen.py
          
      - name: check for file changes
        id: file-check
        run: |
          if [[ -f gogoCookie.txt ]]; then
            echo "file_exists=true" >> $GITHUB_OUTPUT
          fi

      - name: commit files
        if: steps.file-check.outputs.file_exists == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gogoCookie.txt
          git commit -m "Update gogoCookie.txt" -a
          
      - name: push changes
        if: steps.file-check.outputs.file_exists == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PAT }}
          branch: main
